name: Go

on:
  push:
    branches: [main]

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
        IMGUR_CLIENT_SECRET: ${{ secrets.IMGUR_CLIENT_SECRET }}
        IMGUR_REFRESH_TOKEN: ${{ secrets.IMGUR_REFRESH_TOKEN }}


  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
      - name: Clone Repository (1)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Semantic Release
        if: github.event_name != 'pull_request'
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Clone Repository (2)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
